services:
  - type: web
    name: stocksense-ai
    env: node
    plan: free
    buildCommand: npm install --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEWS_API_KEY
        value: 820c22559f3945b7a51feca92a1df50d
      - key: STOCK_API_KEY
        value: 51ZZBUFL7Q681K8C
      - key: FINNHUB_API_KEY
        value: d7l666pr01qm7o0aln7gd7l666pr01qm7o0aln80
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
